# Automatically generated by Pynguin.
import src.clock_display as module_0


def test_case_0():
    bool_0 = False
    list_0 = [bool_0]
    bytes_0 = b'\x02\xdf\x04I\xa8'
    tuple_0 = list_0, list_0, bytes_0
    clock_display_0 = module_0.ClockDisplay(tuple_0)
    assert len(clock_display_0.numbers) == 3
    var_0 = clock_display_0.clone()
    assert len(var_0.numbers) == 3
    bytes_1 = b'\xe6k\xb3\xb8\x8b u1\xda\x94'
    clock_display_1 = module_0.ClockDisplay(bytes_1)
    assert len(clock_display_1.numbers) == 10
    var_1 = clock_display_1.invariant()
    list_1 = [clock_display_1]
    clock_display_2 = module_0.ClockDisplay(list_1)
    assert len(clock_display_2.numbers) == 1
    var_2 = clock_display_1.clone()
    assert len(var_2.numbers) == 10


def test_case_1():
    int_0 = -1436
    tuple_0 = int_0,
    clock_display_0 = module_0.ClockDisplay(tuple_0)
    assert len(clock_display_0.numbers) == 1
    var_0 = clock_display_0.increment()
    assert var_0 is None
